name: Create zip with selected files

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Assemble addon folder
        run: |
          mkdir mastro
          cp -r Handlers mastro/
          cp -r Icons mastro/
          cp -r Keymaps mastro/
          cp -r Nodes mastro/
          cp -r Operators mastro/
          cp -r UI mastro/
          cp -r Utils mastro/
          cp __init__.py mastro/
          cp mastro.blend mastro/
          cp LICENSE.txt mastro/

          mkdir mastro/wheels
          cp wheels/pypdf-6.12.2-py3-none-any.whl mastro/wheels/

      - name: Copy manifest
        run: cp blender_manifest.toml mastro/blender_manifest.toml

      - name: Create ZIP
        run: zip -r mastro.zip mastro/

      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest-mastro
          name: MaStro
          files: mastro.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
